### ISSUE TITLE
Is there an easy set of instructions to build a newer kernel?

### ISSUE THREAD

**Issue by dragon788** [ichinomoto/dm200_debian_kernel#2]
I'm using Google Translate but it doesn't always get the right technical terms.

**Comment by ichinomoto** [comment]
Do you want to make newer version kernel? (4.4 or later) 
sorry, I'm not been try it.

make new kernel from this repository?
if so, refer below.

Make ubuntu 14.04 environment(docker or chroot etc.), then
```
 sudo apt install gcc-arm-linux-gnueabihf
 sudo apt install bc lzop
 export ARCH=arm
 export CROSS_COMPILE=arm-linux-gnueabihf-
 make defconfig dm200_defconfig
 make dep
 make zImage
 ./mkkrnlimg arch/arm/zImage kernel.img
```

If you want to make default kernel, 
use 'onyx_warp_defconfig' instead of 'dm200_defconfig'

**Comment by dragon788** [comment]
I was hoping to try a more recent LTS kernel like 4.4 or 4.14 or 4.19 or maybe a 5.x series because there has been some newer code added for Rockchip boards, but this one might be old enough that not much has changed for a while.

I'll give your directions a shot with a Docker container for 3.x and try to push it over to the device and then maybe try getting a minimal config and compare it to the newer kernels.

**Comment by ichinomoto** [comment]
If you want make 4.4 or later, I recommend to get kernel source code from this rockchip kernel repository.
[https://github.com/rockchip-linux/kernel](https://github.com/rockchip-linux/kernel)
Merge the changes from this kernel. 
I think this will be hard work.

According to this wiki , the 4.4 branch supports RK3128.
And how to build the kernel is shown on this wiki.
[http://opensource.rock-chips.com/wiki_Rockchip_Kernel](http://opensource.rock-chips.com/wiki_Rockchip_Kernel)
